build:
  codetest:
    image: limestreet/php-cli
    environment:
      - PHPCS_DIR=/tmp/phpcs
      - SNIFFS_DIR=/tmp/sniffs
    commands:
      - echo "codetest"
      - git clone -b "2.9" --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
      - git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR
      - git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git $SNIFFS_DIR/PHPCompatibility
      - $PHPCS_DIR/scripts/phpcs --config-set installed_paths $SNIFFS_DIR
      - $PHPCS_DIR/scripts/phpcs -p -s -v -n . --standard=./phpcs.ruleset.xml --extensions=php --ignore=*/node_modules/*,*/vendor/*,class-tgm-plugin-activation.php,class-media-grabber.php
      - jshint .
      - php -v
      - find -L . -name '*.php' -not -path "*node_modules*" -not -path "*vendor*" -not -path "*php-codesniffer*" -not -path ".*" -print0 | xargs -0 -n 1 -P 4 php -l
      - /opt/source/php-5.2.17/bin/php -v
      - find -L . -name '*.php' -not -path "*node_modules*" -not -path "*vendor*" -not -path "*php-codesniffer*" -not -path ".*" -print0 | xargs -0 -n 1 -P 4 /opt/source/php-5.2.17/bin/php -l
    when:
      #event: push
      branch: "!dev"
      
  wptest:
    image: limestreet/apache-php-7
    environment:
      - WP_VERSION=master
      - WP_DEVELOP_DIR=/tmp/wp
    commands:
      - echo "wptest"
      - php -v
      - find -L . -name '*.php' -not -path "*node_modules*" -not -path "*vendor*" -not -path "*php-codesniffer*" -not -path ".*" -print0 | xargs -0 -n 1 -P 4 php -l
      - THEME_SLUG=$(basename $(pwd))
      - mkdir -p $WP_DEVELOP_DIR
      - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
      - THEME_DIR=$WP_DEVELOP_DIR/src/wp-content/themes
      - cd ..
      - cp -r $THEME_SLUG $THEME_DIR
      - cd $WP_DEVELOP_DIR
      - cp wp-tests-config-sample.php wp-tests-config.php
      - sed -i "s/localhost/127.0.0.1:3306/" wp-tests-config.php
      - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
      - sed -i "s/yourusernamehere/wp/" wp-tests-config.php
      - sed -i "s/yourpasswordhere/wp/" wp-tests-config.php
      - wp cli update --yes --allow-root
      - wp core config --dbhost=127.0.0.1:3306 --dbname=wordpress_test --dbuser=wp --dbpass=wp --allow-root # --extra-php <<PHP define( 'WP_DEBUG', true ); PHP
      - wp core install --url=wp.test --title="Local WordPress" --admin_name=admin --admin_email="admin@local.dev" --admin_password="password" --allow-root
      - wp theme activate $THEME_SLUG --allow-root
      - wp tgmpa-plugin install --all --activate --allow-root
      - wp theme activate twentyseventeen --allow-root
      - wp theme activate $THEME_SLUG --allow-root
      - wp rewrite structure '/%postname%/' --allow-root
      - phpunit --version
      - phpunit --group themes

    when:
      #event: push
      branch: "!dev"
  
compose:
  database:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=wp
      - MYSQL_DATABASE=wordpress_test
